package P001_P050;

/*
 Each new term in the Fibonacci sequence is generated by adding the previous 
 two terms. By starting with 1 and 2, the first 10 terms will be:
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 By considering the terms in the Fibonacci sequence whose values 
 do not exceed four million, find the sum of the even-valued terms.
 */
public class P002 {

    public static int solve(int n) {
        int fib;
        int fib1 = 0;
        int fib2 = 1;
        int sum = 0;
        while ((fib = fib1 + fib2) < n) {
            sum += ((fib & 1) == 0) ? fib : 0;
            fib1 = fib2;
            fib2 = fib;
        }
        return sum;
    }

    public static void main(String[] args) {
        System.out.println(P002.solve(4000000));
    }
}
