package P001_P050;

/*
 The sequence of triangle numbers is generated by adding the natural numbers. 
 So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
 The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 Let us list the factors of the first seven triangle numbers:
 1:  1
 3:  1,3
 6:  1,2,3,6
 10: 1,2,5,10
 15: 1,3,5,15
 21: 1,3,7,21
 28: 1,2,4,7,14,28
 We can see that 28 is the first triangle number to have over five divisors.
 What is the value of the first triangle number to have over five hundred divisors?
 */
public class P012 {

    public static int solve(int num) {
        int prod = 0;
        int i = 0;
        while (prod < num) {
            i++;
            long tri = (i * (i + 1)) / 2;
            String s = i + " -> " + tri + ": ";
            prod = 1;
            long div = 2;
            while (tri > 1) {
                int nrDiv = 1;
                while (tri % div == 0) {
                    s += div + ",";
                    tri /= div;
                    nrDiv++;
                }
                prod *= nrDiv;
                div++;
            }
            System.out.println(s + "\b -> " + prod);
        }
        return num;
    }

    public static void main(String[] args) {
        System.out.println(P012.solve(500));
    }
}
